/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sg.jdbcexample;

import com.mysql.cj.jdbc.MysqlDataSource;

import javax.sql.DataSource;
import java.sql.*;
import java.util.Scanner;

/**
 * Has the main method, containing the main menu.
 * @author kylerudy
 */
public class ToDoListMain {

    private static Scanner sc;
    private static DataSource ds;

    public static void main(String[] args) {

        sc = new Scanner(System.in);

        //Set up the data source using getDataSource method created.
        try {
            ds = getDataSource();
        } catch (SQLException e) {
            //Connection to database failed.
            System.out.println("Error connecting to database");
            System.out.println(e.getMessage());
            System.exit(0);
        }

        do {
            System.out.println("To-Do List");
            System.out.println("1. Display List");
            System.out.println("2. Add Item");
            System.out.println("3. Update Item");
            System.out.println("4. Remove Item");
            System.out.println("5. Exit");

            System.out.println("Enter an option:");
            String option = sc.nextLine();
            try {
                switch (option) {
                    case "1":
                        displayList();
                        break;
                    case "2":
                        addItem();
                        break;
                    case "3":
                        updateItem();
                        break;
                    case "4":
                        removeItem();
                        break;
                    case "5":
                        System.out.println("Exiting");
                        System.exit(0);
                }
            } catch (SQLException ex) {
                System.out.println("Error communicating with database");
                System.out.println(ex.getMessage());
                System.exit(0);
            }

        } while (true);
    }

    private static void displayList() throws SQLException {

        try (
            //Try with resources to create connection
            Connection conn = ds.getConnection()
        ) {
            //Create a statement with the connection.
            //Statement okay since query will never change here
            Statement stmt = conn.createStatement();

            //Use executeQuery method of Statement to run query and put into a ResultSet
            ResultSet rs = stmt.executeQuery("SELECT * FROM todo");

            //Loop though ResultSet
            while (rs.next()) {
                //Pull data from the current row and display
                System.out.printf("%s: %s -- %s -- %s\n",
                        rs.getString("id"),
                        rs.getString("todo"),
                        rs.getString("note"),
                        rs.getBoolean("finished")
                );
                System.out.println();
            }
        }
    }

    private static void addItem() throws SQLException {
        System.out.println("Add Item");

        //Collect inputs
        System.out.println("What is the task?");
        String task = sc.nextLine();
        System.out.println("Any additional notes?");
        String note = sc.nextLine();

        try (
            //Try with resources to get connection
            Connection conn = ds.getConnection()
        ) {
            //Prepared statement to avoid SQL injection attacks.
            //Id will be autogenerated by SQL, finished default false.
            String sql = "INSERT INTO todo (todo, note) VALUES (?, ?)";
            PreparedStatement pStmt = conn.prepareCall(sql);

            //Add data at appropriate positions in the query
            pStmt.setString(1, task);
            pStmt.setString(2, note);

            //call executeUpdate() method.
            pStmt.executeUpdate();

            System.out.println("Add Complete");
        }
    }

    private static void updateItem() throws SQLException {
        System.out.println("Update Item");

        //Collect input for id of item to update
        System.out.println("Which item do you want to update?");
        String itemId = sc.nextLine();

        try (
            //Get connection
            Connection conn = ds.getConnection()
        ) {
            //Create prepared statement
            String sql = "SELECT * FROM todo WHERE id = ?";
            PreparedStatement pStmt = conn.prepareCall(sql);
            pStmt.setString(1, itemId);

            //Get the item
            ResultSet rs = pStmt.executeQuery();
            rs.next();

            //Populate an object with the item
            ToDo td = new ToDo();
            td.setId(rs.getInt("id"));
            td.setTodo(rs.getString("todo"));
            td.setNote(rs.getString("note"));
            td.setFinished(rs.getBoolean("finished"));

            //Menu for single update to collect
            //Update object based on user input
            System.out.println("1. ToDo - " + td.getTodo());
            System.out.println("2. Note - " + td.getNote());
            System.out.println("3. Finished - " + td.isFinished());
            System.out.println("What would you like to change?");
            String choice = sc.nextLine();
            switch(choice) {
                case "1":
                    System.out.println("Enter new ToDo:");
                    String todo = sc.nextLine();
                    td.setTodo(todo);
                    break;
                case "2":
                    System.out.println("Enter new Note:");
                    String note = sc.nextLine();
                    td.setNote(note);
                    break;
                case "3":
                    System.out.println("Toggling Finished to " + !td.isFinished());
                    td.setFinished(!td.isFinished());
                    break;
                default:
                    System.out.println("No change made");
                    return;
            }

            //Prepare update sql statement, using existing connection
            //Set data from updated object into the prepared statement
            String updateSql = "UPDATE todo SET todo = ?, note = ?, finished = ? WHERE id = ?";
            PreparedStatement updatePStmt = conn.prepareCall(updateSql);
            updatePStmt.setString(1, td.getTodo());
            updatePStmt.setString(2, td.getNote());
            updatePStmt.setBoolean(3, td.isFinished());
            updatePStmt.setInt(4, td.getId());

            //Apply update, with executeUpdate method.
            updatePStmt.executeUpdate();

            System.out.println("Update Complete");
        }
    }

    private static void removeItem() throws SQLException {
        System.out.println("Remove");

        //Collect user input
        System.out.println("Which item would you like to remove?");
        String itemId = sc.nextLine();

        try(
            //Get the connection
            Connection conn = ds.getConnection()
        ) {
            //Create prepared statment
            String sql = "DELETE FROM todo WHERE id = ?";
            PreparedStatement pStmt = conn.prepareCall(sql);
            pStmt.setString(1, itemId);

            //Apply the delete update using executeUpdate method.
            pStmt.executeUpdate();

            System.out.println("Remove Complete");
        }

    }

    /**
     * Instantiate data source, containing the settings to connect to database.
     * Our MySQL driver lets us instantiate a Mysql data source object and use
     * that to establish communication with the database.
     */
    private static DataSource getDataSource() throws SQLException {

        MysqlDataSource ds = new MysqlDataSource();
        //Server name - local host since connecting to local database.
        ds.setServerName("localhost");
        //Database to use
        ds.setDatabaseName("todoDB");
        //User credentials
        ds.setUser("db_user");
        ds.setPassword("password");
        //Helps server know how to handle dates and times correctly
        ds.setServerTimezone("Europe/London");
        //Toggling SSL encryption - unnecessary for local development.
        ds.setUseSSL(false);
        //Allow JDBC driver to send password to our database securely.
        ds.setAllowPublicKeyRetrieval(true);

        return ds;
    }

}
